server:
  port: 8080

spring:
  application:
    name: gilasw
  datasource:
    url: jdbc:postgresql://localhost:5432/notification_system
    username: your_username
    password: your_password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: info
    org.springframework.web: debug